version: "3.7"

services:
  database:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  server:
    build: .
    image: api-with-docker_server_1
    volumes:
      - .:/node-api
    ports:
      - "3333:3333"
    env_file:
      - .env
    command: yarn dev
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:admin@database:5432/database?schema=public

volumes:
  pgdata:
