version: "3.7"

services:
  database:
    image: postgres:14.3-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=database"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
  server:
    build: .
    depends_on:
      - database
    ports:
      - "333:3333"
    volumes:
      - ./:./
